INSERT INTO TB_CATEGORIA (ID, NOME_CATEGORIA) VALUES(1, 'Algoritmos');
INSERT INTO TB_CATEGORIA (ID, NOME_CATEGORIA) VALUES(2, 'Estrutura de Dados');

INSERT INTO TB_AUTHOR (ID, NOME, EMAIL, DESCRICAO, DAT_CRIACAO) VALUES(1, 'Henrique Amorim', 'henrique@gmail.com', 'Especialista', CURRENT_DATE);